/* USER */
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILURE = 'USER_LOADED_FAILURE';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

/* BANK */

export const BANK_LIST = 'BANK_LIST';
export const BANK_LOADED_SUCESS = 'BANK_LOADED_SUCESS';
export const BANK_LOADED_FAILURE = 'BANK_LOADED_FAILURE';

/* OPERATIONS */

export const OPERATION_LIST = 'OPERATION_LIST';
export const OPERATION_LOADED_SUCESS = 'OPERATION_LOADED_SUCESS';
export const OPERATION_LOADED_FAILURE = 'OPERATION_LOADED_FAILURE';